POST http://localhost:8080/users/register
content-type: application/json

{
    "name": "test",
    "email": "toto@gmail.fr",
    "password": "tata",
    "passwordConfirm": "tata"
}

### 
POST http://localhost:8080/users/login
content-type: application/json

{
    "email": "toto@gmail.fr",
    "password": "tata"
}

### 
GET http://localhost:8080/users/infos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWYwZjZjN2RhZThjNzJjMjRiZjBjOGMiLCJuYW1lIjoidGVzdCIsImVtYWlsIjoidG90b0BnbWFpbC5mciIsImlhdCI6MTU5Mjg1ODQyNiwiZXhwIjoxNTk4MDQyNDI2fQ.j915StCqKC96olf9_C2EI_j9p4k9-XKG-9TiagJkm8c


### 
POST http://localhost:8080/articles/add
content-type: application/json

{
    "title": "Corona",
    "description": "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.",
    "author": "Jasmin"
}

###
PUT http://localhost:8080/articles/edit/5f0a0e44c7b8c451205ea33c
content-type: application/json

{
    "title": "Adventure",
    "description": "Do not join me if you are not motivated"
}

###
DELETE http://localhost:8080/articles/delete/5f0a0e44c7b8c451205ea33c

###
GET http://localhost:8080/articles

###
GET http://localhost:8080/articles/5f09fe58a28a7a165009009b