export const ARTICLES = "https://mernblogapi.herokuapp.com/articles"
export const LOGIN =    "https://mernblogapi.herokuapp.com/users/login"
export const GET_INFOS = "https://mernblogapi.herokuapp.com/users/infos"
export const REGISTER = "https://mernblogapi.herokuapp.com/users/register"
export const EDIT_ARTICLE = "https://mernblogapi.herokuapp.com/articles/edit/"
export const CREATE_ARTICLE = "https://mernblogapi.herokuapp.com/articles/add"
export const DELETE_ARTICLE = "https://mernblogapi.herokuapp.com/articles/delete/"