export const ARTICLES = "http://localhost:8080/articles"
export const LOGIN =    "http://localhost:8080/users/login"
export const GET_INFOS = "http://localhost:8080/users/infos"
export const REGISTER = "http://localhost:8080/users/register"
export const EDIT_ARTICLE = "http://localhost:8080/articles/edit/"
export const CREATE_ARTICLE = "http://localhost:8080/articles/add"
export const DELETE_ARTICLE = "http://localhost:8080/articles/delete/"